# Generated by Django 2.1.5 on 2019-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(),
        ),
    ]
